#!/usr/bin/env bash

function __find_root {
	local DIR=${1:-$PWD}

	if [ $DIR == '/' ]; then
		return 1
	fi

	if [ -d $DIR/includes ]; then
		echo $DIR
		return 0
	fi

	echo $(__find_root `dirname $DIR`)
}

function import {
	if [ -f $1 ]; then
		source $1
		return 0
	fi
	return 1
}

function include {
	local ROOT=$(__find_root)
	local DIR=${ROOT:-$HOME}/includes
	import $DIR/$1 || import $HOME/includes/$1
}

function set-env {
	set -o allexport
	import ${1:-".env"} || import ${2:-".env.default"}
	set +o allexport
}

set-env
