#!/usr/bin/env bash

function has {
	type -t $1 > /dev/null
}

function installer {
	if has apt; then
		echo "apt"
	elif has apk; then
		echo "apk"
	elif has dnf; then
		echo "dnf"
	else
		echo "echo [UNSUPPORTED SYSTEM]"
	fi
}
