#!/usr/bin/env bash

function rand-number {
	local LOWER=${1:-0}
	local UPPER=${2:-10}
	local DIFF=$(( $UPPER - $LOWER + 1))
	echo $(( RANDOM % $DIFF + $LOWER ))
}

function rand-sentence {
	local LOWER=${1:-5}
	local UPPER=${2:-12}
	shuf -n $(rand-number $LOWER $UPPER) /usr/share/dict/words | \
	tr '\n' ' ' | \
	sed 's/.$/./' | \
	sed -e 's/\b\(.\)/\u\1/'
}

function rand-paragraph {
	local LOWER=${1:-3}
	local UPPER=${2:-7}
	local OUTPUT=$(rand-sentence)
	for (( i=1; i<$(rand-number $LOWER $UPPER); i++ )); do
		OUTPUT="$OUTPUT  $(rand-sentence)"
	done
	echo "$OUTPUT"
}
